--- 
apiVersion: template.openshift.io/v1
kind: Template
metadata: 
  name: test-template
objects: 
  - apiVersion: apps/v1
    kind: Deployment
    metadata: 
      labels: 
        app: ${APP_NAME}
      name: ${APP_NAME}
      namespace: default
    spec: 
      replicas: 1
      selector: 
        matchLabels: 
          app: ${APP_NAME}
      template: 
        metadata: 
          labels: 
            app: ${APP_NAME}
        spec: 
          containers: 
            - image: us.icr.io/openshift-tests-paz/express-env-variables:${VERSION}
              name: ${APP_NAME}
              ports: 
                - containerPort: 8080
              env:
              - name: NOMBRE
                value: ${SECRET_NAME}
  - apiVersion: v1
    kind: Service
    metadata: 
      name: service-${APP_NAME}
      namespace: default
    spec: 
      ports: 
        - port: 8080
          targetPort: 8080
      selector: 
        app: ${APP_NAME}
      type: ClusterIP
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata: 
      name: route-${APP_NAME}
      namespace: default
    spec: 
      to: 
        kind: Service
        name: service-${APP_NAME}
parameters: 
  - name: APP_NAME
    value:
  - name: VERSION
    value:
  - name: SECRET_NAME
    value: