---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-deploy
spec:
  params:
    - name: pipeline-debug
      description: Activar para debuggear pipeline. "1" Activado, "0" Desactivado. "0" por defecto
      value: "0"
    - name: repository
      description: Repositorio de git con los YAMLs a aplicar
      default: ""
    - name: branch
      description: Branch donde se trabajará
      default: "master"
    - name: revision
      description: Revisión / commit del repositorio
      default: ""
    - name: ibmcloud-apikey
      description: API Key de IBM Cloud
      default: ""
    - name: cluster-name-or-id
      description: Nombre o ID del clúster
      default: ""
    - name: app-name
      description: Nombre de la aplicación
      default: "test-name"
    - name: image-version
      description: Versión de la imagen, por defecto latest
      default: "latest"
    - name: path-deploy-template
      description: Path al archivo de despliegue
      default: "app"
    - name: secret-name
      description: Nombre en el secret
      default: ""
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
        - name: revision
          value: $(params.revision)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
      workspaces:
        - name: output
          workspace: pipeline-ws
    - name: desplegar-app
      runAfter:
        - git-clone
      taskRef:
        name: task-desplegar-app
      params:
        - name: ibmcloud-apikey
          value: "$(params.ibmcloud-apikey)"
        - name: cluster-name-or-id
          value: "$(params.cluster-name-or-id)"
        - name: path-deploy-template
          value: "$(params.path-deploy-template)"
        - name: app-name
          value: "$(params.app-name)"
        - name: image-version
          value: "$(params.image-version)"
        - name: secret-name
          value: "$(params.secret-name)"
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
